nz_health/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.urls import path
from case_management import views

# Admin Site Config
admin.site.site_header = "NZ Health Admin"
admin.site.site_title = "NZ Health Admin Portal"
admin.site.index_title = "Welcome to NZ Health Researcher Portal"


urlpatterns = [    
    path('admin/', admin.site.urls, name ='admin'), 
    path('accounts/', include('django.contrib.auth.urls')),   
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('create_person',views.create_person, name='create_person'),
    path('people',views.people, name="show_people"),
    path('edit_person/<int:id>',views.edit_person),    
    path('delete_person/<int:id>',views.delete_person),
    path('update_person/<int:id>',views.update_person),   
    path('show_person/<int:id>',views.show_person, name='show_person'), 
    path('create_referral/',views.create_referral, name='create_referral'),
    path('referrals',views.referrals, name='referrals'),
    path('edit_referral/<int:id>',views.edit_referral),   
    path('update_referral/<int:id>',views.update_referral),
    path('delete_referral/<int:id>',views.delete_referral),
    path('show_referral/<int:id>',views.show_referral, name="show_referral"), 
]

case_management/models.py
from django.db import models
from django.conf import settings



# Create your models here.
class Person(models.Model):  
    id = models.BigAutoField(primary_key=True)
    firstName = models.CharField (max_length=40)
    lastName = models.CharField (max_length=40)
    bday = models.DateField(null=True)
   
    def __str__(self):
       return "%s %s" % (self.lastName, self.firstName)

    class Meta:  
        db_table = "person"  

class Referral(models.Model):
    referrer = models.CharField (max_length=40)
    referralDate= models.DateField(null=True)
    note = models.TextField(blank=True)
    person = models.ForeignKey(to=Person, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.referrer

    class Meta:  
        db_table = "referral" 

case_management/forms.py
from django import forms
from django.db.models import fields
from .models import Person, Referral 


class PersonForm(forms.ModelForm):  
    class Meta:  
        model = Person  
        fields = "__all__"  


class ReferralForm(forms.ModelForm):  
    class Meta:  
        model = Referral  
        fields = "__all__"  


      

case_management/views.py
from django.shortcuts import render, redirect
# from django.http import Http404
from .forms import PersonForm, ReferralForm
from .models import Person, Referral 
from django.contrib.auth.decorators import login_required


@login_required
def create_person(request):
    if request.method == "POST":       
        person_form = PersonForm(request.POST)                          
        if person_form.is_valid():
            try:
                person_form.save()                            
                return redirect('/people')
            except:
                pass
    else:
        person_form = PersonForm()              
    return render(request, 'create_person.html', {'person_form': person_form})

@login_required
def people(request):
    people = Person.objects.all()    
    return render(request, "people_index.html",{'people':people})

@login_required
def edit_person(request, id):    
    person = Person.objects.get(id=id)
    return render(request,'edit_person.html',{'person':person})

@login_required
def update_person(request,id):
    person = Person.objects.get(id=id) 
    person_form = PersonForm(request.POST, instance = person)
    if person_form.is_valid():
        person_form.save()
        return redirect("/people") 
    return render(request,'edit_person.html',{'person':person})

@login_required
def delete_person(request,id):  
    person = Person.objects.get(id=id)    
    person.delete()
    return redirect("/people")


@login_required
def show_person (request, id):    
    # person = Person.objects.get(id=id)
    referrals = Referral.objects.filter(person__id = id)
    return render(request,'show_person.html',{'referrals':referrals})

# -----------REFERRALS---------------

@login_required
def create_referral(request):   
    if request.method == "POST":             
        referral_form = ReferralForm(request.POST)                          
        if referral_form.is_valid():
            try:
                referral_form.save()                            
                return redirect('/referrals')
            except:
                pass
    else:
        referral_form = ReferralForm()              
    return render(request, 'create_referral.html', {'referral_form': referral_form})

@login_required
def referrals(request):
    referrals = Referral.objects.all()    
    return render(request, "referrals_index.html",{'referrals':referrals})

@login_required
def edit_referral(request, id):    
    referral = Referral.objects.get(id=id)
    return render(request,'edit_referral.html',{'referral':referral})

@login_required
def update_referral(request,id):
    referral = Referral.objects.get(id=id)
    if request.method == "POST":          
        referral_form = ReferralForm(request.POST, instance = referral)
        if referral_form.is_valid():
            referral_form.save()
        return redirect("/referrals") 
    return render(request,'edit_referral.html',{'referral':referral})

@login_required
def delete_referral(request,id):  
    referral = Referral.objects.get(id=id)    
    referral.delete()
    return redirect("/referrals")

@login_required
def show_referral (request, id):    
    referral = Referral.objects.get(id=id)    
    return render(request,'show_referral.html',{'referral':referral})

case_management/templates/base.html
<!DOCTYPE html>
<html>
   <head>
      <title>{% block title %}NZ Health Case Management{% endblock %}</title>
      {% load static %}  
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'css/style.css' %}"type="text/css" media="all"/>
   </head>
   <body>
      <header>
         <div>
            {% block logo%}
            <img src="../static/images/logo.png"  alt="Fender logo">
            {% endblock %}
            <p>New Zealand Health</p>
         </div>
         <h1> Health Management Case System</h1>
         <div class="login">
            {% if user.is_authenticated %}
            Hi {{ user.username }}!
            <p></p>
            <a id="login" href="{% url 'logout' %}">log out</a></p>
            {% else %}
            <p>You are not logged in</p>
            <a id="login" href="{% url 'login' %}">log in</a>
            {% endif %}       
         </div>
      </header>
      <nav>
         <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'show_people' %}">Patients</a></li>
            <li><a href="{% url 'referrals' %}">Referrals</a></li>
            <li><a href="/admin/">Admin</a></li>
         </ul>
      </nav>
      {% block main %}    
      {% endblock %}
      <footer>
         <p> &copy; NZ Health, 2021</p>
      </footer>
   </body>
</html>

case_management/templates/create_person.html
{% extends 'base.html' %}
{% block main %}
<div class="table">
   <form method="POST" class="post-form" action="/create_person">
      {% csrf_token %}  
      <div class="container">
         <br>  
         <div class="form-group row">
            <label class="col-form-label"></label>  
            <h2>Create Person</h2>
         </div>
         <div class="form-group row">
            <label class="col-form-label">First Name:</label>  
            <div>   
               {{ person_form.firstName }}  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Last Name:</label>  
            <div>   
               {{ person_form.lastName }}  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Birthday:</label>  
            <div>
               {{ person_form.bday}}  
               </input>  
            </div>
         </div>
         <div class="form-group row">
            <label class=" col-form-label"></label>  
            <div>
               <center><button type="submit" class="btn">Submit</button> </center>
            </div>
         </div>
      </div>
   </form>
</div>
{% endblock %}

case_management/templates/create_referral.html
{% extends 'base.html' %}
{% block main %}   
<div class="table">
   <form method="POST" class="post-form" action="/create_referral/">
      {% csrf_token %}  
      <div class="container">
         <br>  
         <div class="form-group row">
            <label class="col-form-label"></label>  
            <h2>Create Referral</h2>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Referrer:</label>  
            <div>  
               {{ referral_form.referrer }}  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Referral Date:</label>  
            <div>  
               {{ referral_form.referralDate }}  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Person:</label>  
            <div>  
               {{ referral_form.person }}  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Note:</label>  
            <div>  
               {{ referral_form.note}}  
            </div>
         </div>
         <br>
         <div class="form-group row">
            <label class="col-form-label"></label>  
            <div>
               <center><button type="submit" class="btn">Submit</button>  </center>
            </div>
         </div>
      </div>
   </form>
</div>
{% endblock %}

case_management/templates/edit_person.html
{% extends 'base.html' %}
{% block main %}
<div class="table">
   <form method="POST" class="post-form" action="/update_person/{{person.id}}">
      {% csrf_token %}  
      <div class="container">
         <br>  
         <div class="form-group row">
            <label class="col-form-label"></label>  
            <h2 >Update Details</h2>
         </div>
         <div >
            <label class="col-form-label">First Name:</label>  
            <div>  
               <input type="text" name="firstName" id="id_firstName" required maxlength="100" value="{{ person.firstName }}" />  
            </div>
         </div>
         <div >
            <label class="col-form-label">Last Name:</label>  
            <div class=" ">  
               <input type="text" name="lastName" id="id_lastName" required maxlength="100" value="{{ person.lastName }}" />  
            </div>
         </div>
         <div >
            <label class="col-form-label">Birthday:</label>  
            <div>  
               <input type="date" name="bday" id="id_bday" required maxlength="254" value="{{ person.bday }}" />  
            </div>
         </div>
         <div >
            <label class="col-form-label"></label>  
            <div>
               <center><button type="submit">Update</button></center>
            </div>
         </div>
      </div>
   </form>
</div>
{% endblock %}

case_management/templates/edit_referral.html
{% extends 'base.html' %}
{% block main %}
<div class="table">
   <form method="POST" class="post-form" action="/update_referral/{{referral.id}}">
      {% csrf_token %}  
      <div class="container">
         <br>  
         <div class="form-group row">
            <label class="col-form-label"></label>  
            <h2>Update Referral</h2>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Referrer</label>  
            <div>  
               <input type="text" name="Referrer" id="id_Referrer" required maxlength="100" value="{{ referral.referrer}}" />  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Referral Date:</label>  
            <div>  
               <input type="text" name="Referral-day" id="id_Referral-date" required maxlength="100" value="{{ referral.referralDate }}" />  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Patient</label>  
            <div>  
               <input type="text" name="Patient" id="id_Patient" required maxlength="254" value="{{ referral.person }}" />  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label">Note</label>  
            <div>  
               <input type="text" name="Note" id="id_Note" required maxlength="254" value="{{ referral.note }}" />  
            </div>
         </div>
         <div class="form-group row">
            <label class="col-form-label"></label>  
            <div>
               <center><button type="submit" class="btn">Update</button></center>
            </div>
         </div>
      </div>
   </form>
</div>
{% endblock %}

case_management/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block main %}    
<main>
   <h2>provide better care outcomes </h2>
   <p><span class="nz-health">Health Management Case System</span> removes the need for spreadsheets and paper-based forms. The smart software solution enables your team to securely access client information on-the-go from multiple devices.</p>
   <p><span class="nz-health">Health Management Case System</span> supporting your teams in delivering better client care, with the right information available, for better outcomes.</p>
</main>
<!-- <aside>
   <div>
      <h2>Cardiac Services</h2>
      <img src="../static/images/Cardiac-Services.jpg" alt="Cardiac Services">
      <p>A private, comprehensive and high quality service was set up in Christchurch in 2003 to meet the growing demand for high quality cardiac services.</p>
   </div>
   <div>
      <h2>Surgical Services</h2>
      <img src="../static/images/surgical-services.jpg" alt="surgical-services">
      <p>Leading the way in providing care and technology, New Zealand Health offers a large variety of surgical services.</p>
   </div>
</aside> -->
{% endblock %}

case_management/templates/people_index.html
{% extends 'base.html' %}
{% block main %}

<div class="table">
    <h2>patient list</h2>
<table id="table-people">    
    <thead>
    <tr>  
        <th>Id</th> 
        <th>Name</th>  
        <th></th>
    </tr>  
    </thead>
    <tbody>  
    {% for person in people %}
    <tr>  
        <td>{{ person.id}}</td>
        <td>{{ person.lastName }} {{ person.firstName }}</td>  
        <td><a href="/show_person/{{ person.id }}">record</a> <a href="/delete_person/{{ person.id }}">delete</a> <a href="/edit_person/{{ person.id }}">edit</a></td>  
    </tr>    
    {% endfor %}      
    </tbody>  
</table> 
<br>
<center><a href="{% url 'create_person' %}">Add New Data</a></center> 
</div>

<!-- <aside>
    <div>
        <h2>Cardiac Services</h2>
        <img src="../static/images/Cardiac-Services.jpg" alt="Cardiac Services">
        <p>A private, comprehensive and high quality service was set up in Christchurch in 2003 to meet the growing demand for high quality cardiac services.</p>
    </div>
    <div>
        <h2>Surgical Services</h2>
        <img src="../static/images/surgical-services.jpg" alt="surgical-services">
        <p>Leading the way in providing care and technology, New Zealand Health offers a large variety of surgical services.</p>
    </div>
</aside> -->
{% endblock %}

case_management/templates/referrals_index.html
{% extends 'base.html' %}
{% block main %}

<div class="table">
    <h2>referral list</h2>
<table id="table-referrals"> 
    <thead>  
    <tr>  
        <th>Patient Id</th>
        <th>Patient Name</th>
        <th>Referrer</th>  
        <th>Referral Date</th>  
        <th></th>                
    </tr>  
    </thead>  
    <tbody>  
    {% for referral in referrals %}
    <tr >
        <td>{{ referral.person.id }}</td>
        <td>{{ referral.person }}</td> 
        <td>{{ referral.referrer}}</td>
        <td>{{ referral.referralDate }}</td>      
        <td>  
            <a href="/edit_referral/{{ referral.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete_referral/{{ referral.id }}">Delete</a>  
        </td>           
    </tr>    
    {% endfor %}      
    </tbody>  
</table>  
<br>
<center><a href="{% url 'create_referral' %}" class="btn btn-primary">Add New Data</a></center> 
</div>

<!-- <aside>
    <div>
        <h2>Cardiac Services</h2>
        <img src="../static/images/Cardiac-Services.jpg" alt="Cardiac Services">
        <p>A private, comprehensive and high quality service was set up in Christchurch in 2003 to meet the growing demand for high quality cardiac services.</p>
    </div>
    <div>
        <h2>Surgical Services</h2>
        <img src="../static/images/surgical-services.jpg" alt="surgical-services">
        <p>Leading the way in providing care and technology, New Zealand Health offers a large variety of surgical services.</p>
    </div>
</aside> -->
{% endblock %}

case_management/templates/show_person.html
{% extends 'base.html' %}
{% block main %}

<div class="table">
    <h2>personal details</h2>
    <table>          
        <thead>  
        <tr>  
            <th>Id</th> 
            <th>First Name</th> 
            <th>Last Name</th>  
            <th>Birthday</th>  
            <th>referrer</th> 
            <th>Referral Date</th>     
            <th></th>     
        </tr>  
        </thead>  
        <tbody>  
        {% for referral in referrals %}
        <tr>  
            <td>{{ referral.person.id}}</td>
            <td>{{ referral.person.firstName }}</td> 
            <td>{{ referral.person.lastName }}</td>  
            <td>{{ referral.person.bday }}</td>
            <td>{{ referral.referrer}}</td>
            <td>{{ referral.referralDate }}</td>          
            <td>  
                <a href="/show_referral/{{referral.id }}">show referal</a>  
            </td>  
        </tr>    
        {% endfor %}      
        </tbody>  
    </table>  
</div>

<!-- <aside>
    <div>
        <h2>Cardiac Services</h2>
        <img src="../static/images/Cardiac-Services.jpg" alt="Cardiac Services">
        <p>A private, comprehensive and high quality service was set up in Christchurch in 2003 to meet the growing demand for high quality cardiac services.</p>
    </div>
    <div>
        <h2>Surgical Services</h2>
        <img src="../static/images/surgical-services.jpg" alt="surgical-services">
        <p>Leading the way in providing care and technology, New Zealand Health offers a large variety of surgical services.</p>
    </div>
</aside> -->
{% endblock %}

case_management/templates/show_referral.html
{% extends 'base.html' %}
{% block main %}

<div class="table">
<table>  
    <h2>referral information</h2>
    <thead>  
    <tr>  
        <th>Patient Id</th> 
        <th>First Name</th> 
        <th>Last Name</th>  
        <th>Birthday</th>  
        <th>Referrer</th> 
        <th>Referral Date</th> 
        <th>Note</th>          
    </tr>  
    </thead>  
    <tbody>  
        <tr>  
        <td>{{ referral.person.id}}</td>
        <td>{{ referral.person.firstName }}</td> 
        <td>{{ referral.person.lastName }}</td>  
        <td>{{ referral.person.bday }}</td>
        <td>{{ referral.referrer}}</td>
        <td>{{ referral.referralDate }}</td> 
        <td>{{ referral.note }}</td>        
       </tr>    
    </tbody>
 </table>  
 <br>
<center><a href="/show_person/{{ referral.person.id}}">go back</a> </center>
</div>
<br>
{% endblock %}